In [42]:
from sklearn.model_selection import train_test_split

In [44]:
import numpy as np
data =  np.genfromtxt("all_data.csv", delimiter=",", dtype=float, filling_values=0.0)
display(data)

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  1., 13., ..., 25., 18.,  0.],
       [ 1.,  0., 25., ...,  1.,  6.,  0.],
       ...,
       [ 1.,  0., 30., ...,  7., 14.,  0.],
       [ 0.,  0., 22., ...,  0.,  0.,  0.],
       [ 1.,  1., 27., ...,  0.,  0.,  0.]])

In [45]:
import torch

In [46]:
X = data[:, :-1]
y = data[:, -1]
print(X.shape, y.shape)

(103905, 22) (103905,)


In [47]:
np.isnan(X).sum()

0

In [48]:
y

array([0., 0., 0., ..., 0., 0., 0.])

In [49]:
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.3)

In [50]:
train_X.shape, train_y.shape, test_X.shape, test_y.shape

((72733, 22), (72733,), (31172, 22), (31172,))

In [51]:
train_y

array([1., 1., 0., ..., 0., 1., 0.])

In [52]:
np.savetxt("train_y.csv", train_y, delimiter=",", fmt='%s')
np.savetxt("test_y.csv", test_y, delimiter=",", fmt='%s')
np.savetxt("train_X.csv", train_X, delimiter=",", fmt='%s')
np.savetxt("test_X.csv", test_X, delimiter=",", fmt='%s')